export default {"board": [
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Ocean"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Ocean"}},
  {"slot": {"slotType": "Ocean"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {
    "tile": {"tileType": "Plants"},
    "slot": {"slotType": "Desert"}
  },
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Ocean"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {
    "tile": {"tileType": "Ocean"},
    "slot": {"slotType": "Desert"}
  },
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Ocean"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Noctis"}},
  {"slot": {"slotType": "Ocean"}},
  {"slot": {"slotType": "Ocean"}},
  {"slot": {"slotType": "Ocean"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {
    "tile": {"tileType": "CapitalCity"},
    "slot": {"slotType": "Ocean"}
  },
  {"slot": {"slotType": "Ocean"}},
  {"slot": {"slotType": "Ocean"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {
    "tile": {"tileType": "Special"},
    "slot": {"slotType": "Desert"}
  },
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Desert"}},
  {"slot": {"slotType": "Ocean"}}
]}